export const bioRubric = {
	"Research Question": {
		0: "The report does not reach a standard described by the descriptors.",
		1: "The research question is stated without context.",
		2: "The research question is stated without context.",
		3: "The research question is outlined within a broad context.",
		4: "The research question is outlined within a broad context.",
		5: "The research question is described within a specific and appropriate context.",
		6: "The research question is described within a specific and appropriate context.",
	},
	"Method Validity": {
		0: "The report does not reach a standard described by the descriptors.",
		1: "Methodological considerations associated with collecting data relevant to the research question are stated.",
		2: "Methodological considerations associated with collecting data relevant to the research question are stated.",
		3: "Methodological considerations associated with collecting relevant and sufficient data to answer the research question are described.",
		4: "Methodological considerations associated with collecting relevant and sufficient data to answer the research question are described.",
		5: "Methodological considerations associated with collecting relevant and sufficient data to answer the research question are explained.",
		6: "Methodological considerations associated with collecting relevant and sufficient data to answer the research question are explained.",
	},
	"Method Reliability": {
		0: "The report does not reach a standard described by the descriptors.",
		1: "The description of the methodology for collecting or selecting data lacks the detail to allow for the investigation to be reproduced.",
		2: "The description of the methodology for collecting or selecting data lacks the detail to allow for the investigation to be reproduced.",
		3: "The description of the methodology for collecting or selecting data allows for the investigation to be reproduced with few ambiguities or omissions.",
		4: "The description of the methodology for collecting or selecting data allows for the investigation to be reproduced with few ambiguities or omissions.",
		5: "The description of the methodology for collecting or selecting data allows for the investigation to be reproduced.",
		6: "The description of the methodology for collecting or selecting data allows for the investigation to be reproduced.",
	},
	Clarity: {
		0: "The report does not reach a standard described by the descriptors.",
		1: "The recording and processing of the data is communicated but is neither clear nor precise.",
		2: "The recording and processing of the data is communicated but is neither clear nor precise.",
		3: "The communication of the recording and processing of the data is either clear or precise.",
		4: "The communication of the recording and processing of the data is either clear or precise.",
		5: "The communication of the recording and processing of the data is both clear and precise.",
		6: "The communication of the recording and processing of the data is both clear and precise.",
	},
	Uncertainty: {
		0: "The report does not reach a standard described by the descriptors.",
		1: "The recording and processing of data shows limited evidence of the consideration of uncertainties.",
		2: "The recording and processing of data shows limited evidence of the consideration of uncertainties.",
		3: "The recording and processing of data shows evidence of a consideration of uncertainties but with some significant omissions or inaccuracies.",
		4: "The recording and processing of data shows evidence of a consideration of uncertainties but with some significant omissions or inaccuracies.",
		5: "The processing of data relevant to addressing the research question is carried out but with some significant omissions, inaccuracies or inconsistencies.",
		6: "The processing of data relevant to addressing the research question is carried out but with some significant omissions, inaccuracies or inconsistencies.",
	},
	Processing: {
		0: "The report does not reach a standard described by the descriptors.",
		1: "Some processing of data relevant to addressing the research question is carried out but with major omissions, inaccuracies or inconsistencies.",
		2: "Some processing of data relevant to addressing the research question is carried out but with major omissions, inaccuracies or inconsistencies.",
		3: "The processing of data relevant to addressing the research question is carried out but with some significant omissions, inaccuracies or inconsistencies.",
		4: "The processing of data relevant to addressing the research question is carried out but with some significant omissions, inaccuracies or inconsistencies.",
		5: "The processing of data relevant to addressing the research question is carried out appropriately and accurately.",
		6: "The processing of data relevant to addressing the research question is carried out appropriately and accurately.",
	},
	Justification: {
		0: "The report does not reach a standard described by the descriptors.",
		1: "A conclusion is stated that is relevant to the research question but is not supported by the analysis presented.",
		2: "A conclusion is stated that is relevant to the research question but is not supported by the analysis presented.",
		3: "A conclusion is described that is relevant to the research question but is not fully consistent with the analysis presented.",
		4: "A conclusion is described that is relevant to the research question but is not fully consistent with the analysis presented.",
		5: "A conclusion is justified that is relevant to the research question and fully consistent with the analysis presented.",
		6: "A conclusion is justified that is relevant to the research question and fully consistent with the analysis presented.",
	},
	"Scientific Context": {
		0: "The report does not reach a standard described by the descriptors.",
		1: "The conclusion makes superficial comparison to the accepted scientific context.",
		2: "The conclusion makes superficial comparison to the accepted scientific context.",
		3: "A conclusion is described that makes some relevant comparison to the accepted scientific context.",
		4: "A conclusion is described that makes some relevant comparison to the accepted scientific context.",
		5: "A conclusion is justified through relevant comparison to the accepted scientific context.",
		6: "A conclusion is justified through relevant comparison to the accepted scientific context.",
	},
	Limitations: {
		0: "The report does not reach a standard described by the descriptors below.",
		1: "The report states generic methodological weaknesses or limitations.",
		2: "The report states generic methodological weaknesses or limitations.",
		3: "The report describes specific methodological weaknesses or limitations.",
		4: "The report describes specific methodological weaknesses or limitations.",
		5: "The report explains the relative impact of specific methodological weaknesses or limitations.",
		6: "The report explains the relative impact of specific methodological weaknesses or limitations.",
	},
	Improvements: {
		0: "The report does not reach a standard described by the descriptors below.",
		1: "Realistic improvements to the investigation are stated.",
		2: "Realistic improvements to the investigation are stated.",
		3: "Realistic improvements to the investigation that are relevant to the identified weaknesses or limitations, are described.",
		4: "Realistic improvements to the investigation that are relevant to the identified weaknesses or limitations, are described.",
		5: "Realistic improvements to the investigation, that are relevant to the identified weaknesses or limitations, are explained.",
		6: "Realistic improvements to the investigation, that are relevant to the identified weaknesses or limitations, are explained.",
	},
};
